### ISSUE TITLE
Can't convert from Essentials_Economy to BagOfGold

### ISSUE THREAD

**Issue by Bergfalkk** [Rocologo/BagOfGold#103]
I have the lastest version of Vault, ProtocolLib, Essentials, PlaceholderAPI.
```
27.05 13:59:50 [Server] INFO Bergfalk issued server command: /bagofgold convert Essentials_Economy BagOfGold
27.05 13:59:50 [Server] INFO Disabling BagOfGold v2.9.9
27.05 13:59:50 [Server] INFO unhooked from Vault
27.05 13:59:51 [Server] INFO Closing database connection.
27.05 13:59:51 [Server] INFO Enabling BagOfGold v2.9.9
27.05 13:59:51 [Server] WARN Enabled plugin with unregistered PluginClassLoader BagOfGold v2.9.9
27.05 13:59:51 [Server] INFO Config.yml was backed up to plugins/BagOfGold/backup/config.yml.bak8
27.05 13:59:51 [Server] INFO Database version 3 detected.
27.05 13:59:51 [Server] INFO Enabling compatibility with ProtocolLib (4.5.0).
27.05 13:59:51 [Server] INFO class one.lindegaard.BagOfGold.bank.BagOfGoldBankerTrait
27.05 13:59:51 [Server] INFO [ERROR] MobHunting could not register with [Citizens] please check if [Citizens] is compatible with the server [1.15.2-R0.1-SNAPSHOT]
27.05 13:59:51 [Server] INFO Enabling compatibility with Essentials (2.17.1.0)
27.05 13:59:51 [Server] INFO Enabling compatibility with PlaceholderAPI (2.10.6).
27.05 13:59:51 [Server] INFO [BagOfGold][Economy] Vault found: Waiting
27.05 13:59:51 [Server] INFO hooked into Vault
27.05 13:59:51 [Server] ERROR null
27.05 13:59:51 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'bagofgold' in plugin BagOfGold v2.9.9
27.05 13:59:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1094) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1087) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1048) ~[patched_1.15.2.jar:git-Paper-284]
27.05 13:59:58 [Multicraft] Skipped 9 lines due to rate limit (30/s)
```

**Comment by Bergfalk-Krieger** [comment]
I installed MobHunting and Citizens, but doesn't work :C

**Comment by Rocologo** [comment]
NPC's does not work on al patched PaprerSpigot servers. Please make sure the Citizens works before testing BagOfGold
