### ISSUE TITLE
Bag of gold first time install

### ISSUE THREAD

**Issue by thomasctobin** [Rocologo/BagOfGold#143]
[13:00:48] [Server thread/INFO]: [BagOfGold] Enabling BagOfGold v4.5.4
[13:00:48] [Server thread/INFO]: [BagOfGold] Config.yml was backed up to plugins\BagOfGold\backup\config.yml.bak5
[13:00:48] [Server thread/INFO]: [BagOfGold] Database version 3 detected.
[13:00:48] [Server thread/INFO]: [BagOfGold]Copying players from BagOfGold til BagOfGoldCore database
[13:00:48] [Server thread/ERROR]: Error occurred while enabling BagOfGold v4.5.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "one.lindegaard.BagOfGold.storage.DataStoreManager.flush()" because the return value of "one.lindegaard.BagOfGold.BagOfGold.getDataStoreManager()" is null
        at one.lindegaard.BagOfGold.storage.SQLiteDataStore.migrateDatabaseLayoutFromV3ToV4(SQLiteDataStore.java:221) ~[?:?]
        at one.lindegaard.BagOfGold.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:143) ~[?:?]
        at one.lindegaard.BagOfGold.BagOfGold.onEnable(BagOfGold.java:144) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3728-Spigot-514cf03-15a3eac]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:00:48] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with BagOfGold (4.5.4)

**Comment by Rocologo** [comment]
tryteh following
1) Stop your server
2) change database_version to 4 in bagofgold config.yml
3 ) Start your server

**Comment by Rocologo** [comment]
Or try snapshot 131 or newer

https://jenkins.lindegaard.one/job/BagOfGold/
