### ISSUE TITLE
Changed economy from false to true and got error. spigot 1.13.1. but this happen only once for me

### ISSUE THREAD

**Issue by Optimusik** [Rocologo/BagOfGold#34]
[09:48:45 WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'balance' at row 1
[09:48:45 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3974)
[09:48:45 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
[09:48:45 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[09:48:45 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[09:48:45 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
[09:48:45 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[09:48:45 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[09:48:45 WARN]:        at me.xanium.gemseconomy.data.MySQLStorage.saveAccount(MySQLStorage.java:343)
[09:48:45 WARN]:        at me.xanium.gemseconomy.economy.Account.deposit(Account.java:49)
[09:48:45 WARN]:        at me.xanium.gemseconomy.vault.GemsEco.depositPlayer(GemsEco.java:117)
[09:48:45 WARN]:        at com.earth2me.essentials.register.payment.methods.VaultEco$VaultAccount.set(VaultEco.java:151)
[09:48:45 WARN]:        at com.earth2me.essentials.User.setMoney(User.java:431)
[09:48:45 WARN]:        at net.craftersland.essentials.mysql.DataHandler.reloadEssentialsDataFile(DataHandler.java:259)
[09:48:45 WARN]:        at net.craftersland.essentials.mysql.events.PlayerJoin.onJoin(PlayerJoin.java:31)
[09:48:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:48:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:48:45 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:48:45 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[09:48:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[09:48:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:48:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[09:48:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482)
[09:48:45 WARN]:        at net.minecraft.server.v1_13_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:264)
[09:48:45 WARN]:        at net.minecraft.server.v1_13_R2.LoginListener$1.run(LoginListener.java:178)

**Comment by Rocologo** [comment]
Do you if the balance was very very very high?

**Comment by Optimusik** [comment]
Yes. i think about 99999999999

**Comment by Rocologo** [comment]
Hmm, i actually dont know the limit of the balance... I think the Database type i a REAL / DOUBLE.

**Comment by Rocologo** [comment]
In latest build you cant give/drop/take more than 100 bags * limitPerBag(10000)

https://fractal.lindegaard.one:8181/job/BagOfGold/

I think will solve this issue. Also I cant change the max/min numbers in the database.
