### ISSUE TITLE
NPE when using /bagofgold npc select

### ISSUE THREAD

**Issue by Jacxk** [Rocologo/BagOfGold#5]
```
java.lang.NullPointerException
        at one.lindegaard.BagOfGold.commands.NpcCommand.onCommand(NpcCommand.java:164) ~[?:?]
        at one.lindegaard.BagOfGold.commands.CommandDispatcher.onCommand(CommandDispatcher.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        ... 15 more
```

**Comment by Rocologo** [comment]
Please post the exact command you run and please show me the full error text.

**Comment by Jacxk** [comment]
Sorry for the late (i day) reply but here you go
```
[12:44:45 INFO]: By_Jack issued server command: /bog npc select
[12:44:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bog' in plugin BagOfGold v0.9.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at one.lindegaard.BagOfGold.commands.NpcCommand.onCommand(NpcCommand.java:164) ~[?:?]
        at one.lindegaard.BagOfGold.commands.CommandDispatcher.onCommand(CommandDispatcher.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        ... 15 more
```

**Comment by Rocologo** [comment]
You can use "/npc select instead", until i get this fixed.

**Comment by Rocologo** [comment]
This is fixed in next release.

My guess that you did not look at the npc while typeing the command? This would cause this error.
