### ISSUE TITLE
Null Pointer error spamming console

### ISSUE THREAD

**Issue by kelso6969** [Rocologo/BagOfGold#53]
[03:05:26] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to BagOfGold v2.5.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:945) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at one.lindegaard.BagOfGold.rewards.Reward.isReward(Reward.java:277) ~[?:?]
        at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.canPickupMoney(BagOfGoldItems.java:318) ~[?:?]
        at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.onPlayerMoveOverRewardEvent(BagOfGoldItems.java:711) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        ... 15 more

**Comment by kelso6969** [comment]
after beta version, I still get this.
[21:11:42 ERROR]: Could not pass event PlayerMoveEvent to BagOfGold v2.5.2-SNAPSHOT-B186
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:945) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at one.lindegaard.BagOfGold.rewards.Reward.isReward(Reward.java:276) ~[?:?]
        at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.canPickupMoney(BagOfGoldItems.java:319) ~[?:?]
        at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.onPlayerMoveOverRewardEvent(BagOfGoldItems.java:723) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-8ede039-d0a9130]
        ... 15 more

**Comment by Rocologo** [comment]
Hmm.... do you know what trigger this error ? Are you doing something special?

The part of the code which fails is rather simple and I cant see what should trigger an NPE exception :-(

```
	public static boolean isReward(ItemStack itemStack) {
		if (itemStack != null && itemStack.hasItemMeta() && itemStack.getItemMeta().hasLore()) {
			for (int i = 0; i < itemStack.getItemMeta().getLore().size(); i++) {
				if (itemStack.getItemMeta().getLore().get(i).equals("Hidden:" + MH_REWARD_BAG_OF_GOLD_UUID)
						|| itemStack.getItemMeta().getLore().get(i).equals("Hidden:" + MH_REWARD_KILLED_UUID)
						|| itemStack.getItemMeta().getLore().get(i).equals("Hidden:" + MH_REWARD_KILLER_UUID)
						|| itemStack.getItemMeta().getLore().get(i).equals("Hidden:" + MH_REWARD_ITEM_UUID)) {
					return true;
				}
			}
		}
		return false;
	}

```

And it is actually this line, which is the problem...

`if (itemStack.getItemMeta().getLore().get(i).equals("Hidden:" + MH_REWARD_BAG_OF_GOLD_UUID)`

**Comment by kelso6969** [comment]
Sadly, I do not know the trigger. Perhaps when in gamemode 1 and it starts duplicating the fake bags of gold and telling you its a fake reward?

**Comment by Rocologo** [comment]
Okay. I have made a change which MIGHT help. (Im not 100% sure because I have never got the error on my own server, so Im not able to check if this fixes the error.

I have also worked (in the weekend) on a better solution for the Fake reward problem in Creative mode. I would appreciate if you could help me with the testing. 

You should not put the snapshots on a production server with a lot of players until it has been tested properly :-) I have made a lot of changes in the part of the source code, where you move Bags around. (in, out or between inventories and using shift click, or pressing hotkeys while pointing at items and so on.) 

I have made a new build: https://fractal.lindegaard.one:8181/job/BagOfGold/187/

If you get error again, the please post the new error here.

**Comment by kelso6969** [comment]
[15:42:33 ERROR]: Could not pass event PlayerMoveEvent to BagOfGold v2.5.2-SNAPSHOT-B186
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:945) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at one.lindegaard.BagOfGold.rewards.Reward.isReward(Reward.java:275) ~[?:?]
        at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.canPickupMoney(BagOfGoldItems.java:319) ~[?:?]
        at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.onPlayerMoveOverRewardEvent(BagOfGoldItems.java:723) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        ... 15 more



Not sure if its the same, and certainly not seeing it a lot. Just happen to check console and it was there. FYI

**Comment by kelso6969** [comment]
I'll put it in to production during tonights auto-restart and will let you know, thanks!
