### ISSUE TITLE
Errors upon joining or opening inventory.

### ISSUE THREAD

**Issue by NABrr** [Rocologo/BagOfGold#64]
Repeatedly having errors with any version after 2.5.4 on my 1.13.2 server making the plugin inoperable even though it shows active in the plugin list. Unsure what the cause may be. The following is the join error.
`[14:39:15] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BagOfGold v2.5.9
java.lang.NoClassDefFoundError: one/lindegaard/MobHunting/MobHunting
	at one.lindegaard.BagOfGold.util.Misc.round(Misc.java:12) ~[?:?]
	at one.lindegaard.BagOfGold.rewards.EconomyManager.adjustAmountOfMoneyInInventoryToPlayerBalance(EconomyManager.java:453) ~[?:?]
	at one.lindegaard.BagOfGold.PlayerBalanceManager.onPlayerJoin(PlayerBalanceManager.java:138) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-625]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-625]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-625]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-625]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: one.lindegaard.MobHunting.MobHunting
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-625]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-625]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 18 more`

**Comment by Rocologo** [comment]
Fixed in newest snapshot. 
https://fractal.lindegaard.one:8181/job/BagOfGold/261/
I have to follow up on other tickets and then I will make e v2.6.0 release 

Please confirm if it is fixed on your server?

**Comment by NABrr** [comment]
It appears to be working properly however, there's an error thrown in console'
`[01:06:02] [Server thread/INFO]: [BagOfGold] mTranslationTable has not key: bagofgold.reward.name`

And NPC bankers no longer work for me when they do in with version 2.5.4. I see you have a message stating that it only works on Spigot servers. Paper is a fork of Spigot, and as stated, the plugin back in version 2.5.4 works perfectly.

**Comment by NABrr** [comment]
I'm also receiving the following messages in console:
`[01:11:38] [Server thread/INFO]: [BagOfGold] mTranslationTable has not key: bagofgold.commands.bank.description
[01:11:38] [Server thread/INFO]: [BagOfGold] MobHunting could not find key: bagofgold.commands.bank.description
[01:11:38] [Server thread/INFO]: [BagOfGold] mTranslationTable has not key: bagofgold.commands.convert.description`

I'm afraid I may be a one off case it seems. Apologies if it's a bother.
