### ISSUE TITLE
database:type:mysql connects to DB but fails on player login.

### ISSUE THREAD

**Issue by bwl** [Rocologo/BagOfGold#65]
Switching to mysql storage method. Plugin seems to connect and create the tables. Seems that it is failing on playerInsert. I tried upping the LAST_LOGON field length but it didn't fix.

Happy to provide more information if needed. Also to note: I'm using MariaDB not official mysql.

thanks Roco

Console Error Here
```
[16:37:49] [User Authenticator #2/INFO]: UUID of player XXX is XXXX-XXXX-XXXX-XXXX
[16:37:50] [MH TaskThread/WARN]: one.lindegaard.BagOfGold.storage.DataStoreException: java.sql.BatchUpdateException: Data truncation: Out of range value for column 'LAST_LOGON' at row 1
[16:37:50] [MH TaskThread/WARN]:        at one.lindegaard.BagOfGold.storage.DatabaseDataStore.insertPlayerSettings(DatabaseDataStore.java:278)
[16:37:50] [MH TaskThread/WARN]:        at one.lindegaard.BagOfGold.storage.asynch.PlayerSettingsRetrieverTask.run(PlayerSettingsRetrieverTask.java:37)
[16:37:50] [MH TaskThread/WARN]:        at one.lindegaard.BagOfGold.storage.asynch.PlayerSettingsRetrieverTask.run(PlayerSettingsRetrieverTask.java:13)
[16:37:50] [MH TaskThread/WARN]:        at one.lindegaard.BagOfGold.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:298)
[16:37:50] [MH TaskThread/WARN]: Caused by: java.sql.BatchUpdateException: Data truncation: Out of range value for column 'LAST_LOGON' at row 1
[16:37:50] [MH TaskThread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:37:50] [MH TaskThread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[16:37:50] [MH TaskThread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:37:50] [MH TaskThread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1823)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1307)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[16:37:50] [MH TaskThread/WARN]:        at one.lindegaard.BagOfGold.storage.DatabaseDataStore.insertPlayerSettings(DatabaseDataStore.java:271)
[16:37:50] [MH TaskThread/WARN]:        ... 3 more
[16:37:50] [MH TaskThread/WARN]: Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'LAST_LOGON' at row 1
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[16:37:50] [MH TaskThread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1801)
[16:37:50] [MH TaskThread/WARN]:        ... 6 more
```

Plugin connects to the database and creates tables. But I have not seen it create rows:

![Screen Shot 2019-05-26 at 12 42 07 PM](https://user-images.githubusercontent.com/7365/58384766-e509a980-7fb3-11e9-9c64-7f56ee241a25.png)

**Comment by bwl** [comment]
update: i tested with mysql-server and am getting the same error

**Comment by bwl** [comment]
Was able to force the issue by changing the column type from int, length 11 to varchar, length 13

I found in your code that LAST_LOGON will be milliseconds since epoch - which currently is a 13 digit number. ( https://currentmillis.com/ )

I tried int, length 13 first but got same error.

**Comment by Rocologo** [comment]
hmm LAST_LOGON was created as a INTEGER default 0, i have changed this to BIGINT this should fix the problem. (I Hope)

**Comment by Rocologo** [comment]
If you are able to help testing, then please test this build:

https://fractal.lindegaard.one:8181/job/BagOfGold/264/

**Comment by Rocologo** [comment]
It might be a problem that your database contains LAST_LOGON and LAST_INTEREST now. If you know howto, you can delete these two columns and then restart the server to get the them created again.

**Comment by Rocologo** [comment]
Or if you are able to change the datatype to BIGINT this should work too.

**Comment by bwl** [comment]
Thanks @Rocologo will test this evening - much appreciated
