### ISSUE TITLE
Feature request: Physical bank

### ISSUE THREAD

**Issue by VreyaViress** [Rocologo/BagOfGold#73]
[https://i.imgur.com/CPjaa0l.png](url) (Towny bank using Gringotts as an example)

Currently, Bag Of Gold's bank system is kind of virtual, as the money deposited is somehow stored in the server instead, stopping being physically available once in there.

It would be, of course, pretty easily to simply have a bunch of gold blocks stored at some building, when using Gringotts Style option in the config. However, you could not know how much money you actually have.

Therefore, a way to either use a chest where you can deposit the Gringotts style blocks, or maybe (even better) a way for the Bag of Gold plugin to detect the value of the blocks stored on the ground at some building, would keep the physical impression while, at the same time, allowing you to store the money somewhere else that isn't your inventory.

On the other hand, there's this plugin Towny, which has a bank fro plot claiming porpuses. On Gringotts, you can manage the money stored in that bank through signs. However, when using Bag of Gold, the physical money you once had in your inventory, turns virtual once you deposit it in the town's bank. My suggestion here would be to either have some kind of add-on to make a new plot type called "Bank", where every block configured with Bag of Gold Gringotts style would be counted for the amount of money available on your town's bank.

**Comment by Rocologo** [comment]
So I understand that you would like to have a Bank where the money is stored safely as items/blocks.

But why dont you store the items in a protected chest then? I dont understand what the difference is? 

Or you could use ShopArea and make small rooms (banks) where your players can buy a room (a kind of "safe", this is actually my own plan for my server - making a bank with "ShopArea rooms". The player can the buy a room and store their money in the room.

**Comment by VreyaViress** [comment]
The point is making it quantifiable.

Make it so you can know how much money you have stored in a physical bank. Also, making Towny's bank physical.

**Comment by AnthonyPaulO** [comment]
> [https://i.imgur.com/CPjaa0l.png](url) (Towny bank using Gringotts as an example)
> 
> Currently, Bag Of Gold's bank system is kind of virtual, as the money deposited is somehow stored in the server instead, stopping being physically available once in there.
> 
> It would be, of course, pretty easily to simply have a bunch of gold blocks stored at some building, when using Gringotts Style option in the config. However, you could not know how much money you actually have.
> 
> Therefore, a way to either use a chest where you can deposit the Gringotts style blocks, or maybe (even better) a way for the Bag of Gold plugin to detect the value of the blocks stored on the ground at some building, would keep the physical impression while, at the same time, allowing you to store the money somewhere else that isn't your inventory.
> 
> On the other hand, there's this plugin Towny, which has a bank fro plot claiming porpuses. On Gringotts, you can manage the money stored in that bank through signs. However, when using Bag of Gold, the physical money you once had in your inventory, turns virtual once you deposit it in the town's bank. My suggestion here would be to either have some kind of add-on to make a new plot type called "Bank", where every block configured with Bag of Gold Gringotts style would be counted for the amount of money available on your town's bank.

Wouldn't the Banker serve the same purpose? I had the same gripe when I first used the mod but then realized it supported an actual banker via '/bag banker create' command. I build a bank structure and create my banker inside and 'presto', I now have a physical bank I can go to in order to deposit and withdraw money, makes it all seem real rather than virtual via commands.

**Comment by Rocologo** [comment]
I like the idea about physical money in the bank. I have thought about a solution where chests is vaults. One chest per player and the chest can only be opened by rhe owner. A chest protection plugin like LWC could be used for this.

**Comment by rackgaming** [comment]
I hope you plan to add this with a sign fix, I currently used griefprevention and last time I attempted using the signs, they had permission to use the signs but it did nothing on interact.

**Comment by rackgaming** [comment]
I still think we need this in 2022.

**Comment by rackgaming** [comment]
but I use griefprevention also

**Comment by Rocologo** [comment]
Hi. I still like the idea about a physical bank. But I not sure how the concept should be and how the bank should look like.

**Comment by rackgaming** [comment]
Well I am currently talking with XVaults and he wants to implement support so that a chest with a sign having [vault] can be a personal bank inside a land claimed area

**Comment by rackgaming** [comment]
So he wants to add bagofgold support

**Comment by rackgaming** [comment]
So that players can put their bagofgold inside a vault claimed chest in his plugin and the chest can be opened to access the bank money

**Comment by rackgaming** [comment]
Their personal bank money but I think that is the concept

**Comment by Rocologo** [comment]
If he needs help I will gladly help

**Comment by rackgaming** [comment]
Gringotts basically uses real minecraft items like emerald diamond whatever you choose

**Comment by rackgaming** [comment]
Thats the physical item part from what op is asking

**Comment by Rocologo** [comment]
I know how Gringotts works. :-)

**Comment by Rocologo** [comment]
BagOfGold can be configured to work like Gringotts

**Comment by Rocologo** [comment]
Im still think that I would be able to make a physical bank using a Workdguard region containing chests for storage of the bags and and the banker or the signs inside the region would access the chests/bags.

**Comment by rackgaming** [comment]
OH! I see what OP is saying my bad, sorry. Basically the BagOfGold on ground in a towny ect is still counted as their money

**Comment by Rocologo** [comment]
I worried about one thing. How should players who is not playing on the server anymore be handled in a physical bank be handled? After some time the bank will be filled will money from players who is not on the server any more.

**Comment by rackgaming** [comment]
Well if they leave, have the items unload but stored in player data then when they come back it loads their currency back in

**Comment by rackgaming** [comment]
Or the towny owner should have perms to remove reaidents bank currency and if they leave that towny the money should go back to the original players hand

**Comment by Rocologo** [comment]
But if the items in the bank is unloaded what is the point then? Then you make them virtual again? You make me think about what the point is? Why store the bags in a bank, if the disapear when the player leaves and nobody can see or interact with the money in the bank? 

What is the used case for the player when he enter the Bank?

**Comment by Rocologo** [comment]
I mean if you cant see the money in the bank, why then store them in a chest in a bank ?

**Comment by rackgaming** [comment]
Well we're talking about someone who is never coming back. Am a bit confused if we're talking about self owned land claims or towny and faction

**Comment by Rocologo** [comment]
I am a bit confused as well :-) 

At the moment we are brainstorming. I will not start coding until I am sure that we somehow agree about the solution and agree about how this should work when you are a Player and when you are Admin.

**Comment by rackgaming** [comment]
Well most of the time staff members have the final right to decide on what to do. But the same case scenario happens in a towny, you have residents and the towny owner along with his trusty studs should have the final say on what to do. e.g. refund the item virtually back to the player, keep it for themselves or split it amongst the residents.

**Comment by rackgaming** [comment]
For the grief prevention land claims, idc what happens with their money. the money in the bank is still both phyiscal and virtual at the same time. So what I mean is, your gold is in your land claim on your ground, its your cash.

**Comment by Rocologo** [comment]
This is what I was thinking 
1) we have an area (a Worldguard region, A Plot, A Towny Area, an AreaShop) 
2) In the area and Admin / Owner has build a "house" - and we call this a bank. 
3) In the bank we have some chests for storing bags. 
4) We have a Banker (NPC) or some signs inside the region/area to get the balance, withdraw and deposit money
5) The chests is protected buy either Worldguard/Towny/GrieftPrevention or another protection plugin

Notice that there is no ownership of a bag (like a coin or a banknote - they dont have a ownership. If someone finds a banknote, you  cant tell who dropped it) 

What more should the Player be able to do? 

And the Admin must have some commands as well, so he can maintain the bank.

**Comment by rackgaming** [comment]
![image](https://user-images.githubusercontent.com/7550358/203074245-1ef5ac82-b830-4993-b152-dc0217e15cc7.png)
Basically this as well, they place a bag on the ground in their GP claimed land, the bags should still count towards their cash amount(And of course if they place a certain amount let's say, 1 bag each is 50 gold placed on ground, then they pick it up, it still stays as the virtual cash) of course if they walk away, you could have it so they don't see it since they are not inside their land claim.

**Comment by Rocologo** [comment]
> then they pick it up, it still stays as the virtual cash

This is NOT possible. If they pick up the bags it will be like if they Withdraw the money from the bank.

**Comment by rackgaming** [comment]
or just keep it physical then

**Comment by rackgaming** [comment]
Well I use WorldGuard for my spawn area but for the land claims, it is based off of GriefPrevention(Because I rather keep it simple to a golden shovel then some fancy smancy type to claim your own land and name it).

**Comment by rackgaming** [comment]
Yea, the chest part is first step so I hope the XVaults guy comes around and you guys can work together.

**Comment by Rocologo** [comment]
> Yea, the chest part is first step so I hope the XVaults guy comes around and you guys can work together.

You talked about XVault yesterday? What is XVault? I only know the Vault plugin ?

**Comment by rackgaming** [comment]
https://www.spigotmc.org/resources/xvaults-player-vaults-1-18.99163/ It's a GUI based vault plugin where you can drag n drop to store items in a vault based on permission similiar to a backpack or extra storage.

**Comment by rackgaming** [comment]
![image](https://user-images.githubusercontent.com/7550358/203079405-c2f52610-cba9-416e-8ea8-a38397e4582a.png)

**Comment by Rocologo** [comment]
Update: 

1) we have an area (a Worldguard region, a Grief Prevention Claim, a Plot, A Towny Area, an AreaShop) This is used to make sure that no one can break the bank and the chests. I will probably use Worildguard, because I already know to hook into Worldguard and know how to setup protection.
2) In the area and Admin / Owner has build a "house" - and we call this a bank. 
3) In the bank we have some chests for storing bags. 
4) The chests can be one or more chests per player and each chest inside the bank has an ownership. This way the Bank Owner can place Empty chests in the bank for players. Each cheat has ownership ans a sign can show the owner and balance and maybe a last seendate
5) We have a Banker (NPC) or some signs inside the region/area to get the balance, withdraw and deposit money - or the player can open his OWN chests and store money in the cheast, but not other owners chests. (Admins could be allowed to do so).
6) The chests is protected buy either Worldguard/Towny/GrieftPrevention or another protection plugin

Notice that there is no ownership of a bag (like a coin or a banknote - they dont have a ownership. If someone finds a banknote, you  cant tell who dropped it) 

What more should the Player be able to do? 

And the Admin must have some commands as well, so he can maintain the bank.

**Comment by rackgaming** [comment]
Oh I forgot to ask, about the Citizens2, do we need the premium version of Citizens2 or can it be used with the free version?

**Comment by Rocologo** [comment]
> Oh I forgot to ask, about the Citizens2, do we need the premium version of Citizens2 or can it be used with the free version?

Free is fine. The Banker already works with the free version.

**Comment by rackgaming** [comment]
Well what do you know, thank you for letting me know because on the page of BagOfGold, it just states Citizens2 lol.

**Comment by rackgaming** [comment]
> > Well what do you know, thank you for letting me know because on the page of BagOfGold, it just states Citizens2 lol.
> 
> ??? but it does not say a Paid version? :-)

Well some people don't understand that because they'll just go to that page and it will say $10.00 then they think oh BOY, time to get out my wallet :D

**Comment by rackgaming** [comment]
Also why don't you make a discord?? Wouldn't it be easier instead of spamming the github page?

**Comment by Rocologo** [comment]
> > > Well what do you know, thank you for letting me know because on the page of BagOfGold, it just states Citizens2 lol.
> > 
> > 
> > ??? but it does not say a Paid version? :-)
> 
> Well some people don't understand that because they'll just go to that page and it will say $10.00 then they think oh BOY, time to get out my wallet :D

I have never paid for a plugin and I dont want to and mine has always been free. This is a hobby for me. Its free when you download Citizens from theit Jenkins server. http://ci.citizensnpcs.co/job/Citizens2

**Comment by Rocologo** [comment]
> Also why don't you make a discord?? Wouldn't it be easier instead of spamming the github page?

I have a Discord Server, but I dont have the time to support and answer alot of questions :-D

**Comment by rackgaming** [comment]
Ah well it's not on the page and time doesn't matter as long as people get help, they can just be patient so I'd still like to join it.

**Comment by Rocologo** [comment]
And I am always happy when someone makes a donation and I can tell you I spend ALOT of time on this :-)

**Comment by rackgaming** [comment]
`[15:11:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bagofgold' in plugin BagOfGold v4.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
	at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:358) ~[Citizens-2.0.30-b2765.jar:?]
	at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:109) ~[Citizens-2.0.30-b2765.jar:?]
	at net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:52) ~[Citizens-2.0.30-b2765.jar:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:48) ~[Citizens-2.0.30-b2765.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:275) ~[Citizens-2.0.30-b2765.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:253) ~[Citizens-2.0.30-b2765.jar:?]
	at one.lindegaard.BagOfGold.commands.NpcCommand.onCommand(NpcCommand.java:196) ~[BagOfGold-4.2.0.jar:?]
	at one.lindegaard.BagOfGold.commands.CommandDispatcher.onCommand(CommandDispatcher.java:96) ~[BagOfGold-4.2.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more`

**Comment by Rocologo** [comment]
> Am a bit confused because I tried creating a bank NPC on the free version and it did not do anything but give a giant error.

Im pnly using the free version. It is important that you use a version which works on your server version. Im on 1.19.2 so I can use the newest version.

**Comment by rackgaming** [comment]
I'm on paper 1.19 using the latest build 4 days ago.

**Comment by Rocologo** [comment]
> I'm on paper 1.19 using the latest build 4 days ago.

Check your server log. Does Citizens2 enable  without errors ?

**Comment by rackgaming** [comment]
Citizens2 is the one having the error, posted it on their discord. Waiting for a response.

**Comment by Rocologo** [comment]
I also notice that you use Paper-Spigot Im always using Spigot MC. I dont know if there is a difference.

**Comment by rackgaming** [comment]
People usepaper spigotbecause its more optimized then spigot

**Comment by rackgaming** [comment]
Essentially their the same but one is less performance impacted

**Comment by rackgaming** [comment]
I spoke with the devs of NPC and they said that they do not support non patched versions which means, I will unfortunately have to update to 1.19.2 paper MC for the NPC's to work. Which is a good thing to note on the spigot page.

**Comment by Rocologo** [comment]
it shouldnt be a big problem to update to 1.19.2 you will find the most plugins which works on 1.19 also works on 1.19.2 or has been updated.

**Comment by Rocologo** [comment]
I have actually started to make the code for the the Bankvault features :-) 

Now I have to decide
1) how the admin should create the Bank and define which chests are used as Bankvaults inside the Bank. 
2) How the players should claim a chest and use it as a bankvault for his bags.

I can either use commands like 
/bag bank create bankname (difining the area)
/bag vault create (admin define the chest as bankvault)
/bag vault remove (admin remove the bankvault from the bank)
/bag vault claim (the player claims the bankvaukt)
or the player claims a chest first time he moves a bag into the Chest.
or the player could claim the chest by placing a sign on the chest with [bankvault] 

I think that it should have a cost to claim a chest (price defined in config)

Also I think about making a sign placed over the chest or attached to the chest, with some information like 
[Bankvault]
ownername
balance 
last seen date (if I can find this) 

what do you think?

**Comment by Rocologo** [comment]
I think I prefer a solution where the admin place a sign on top of the Chest, but Im not sure because it limits the admin posibility to make his design

**Comment by rackgaming** [comment]
Bank defined area sounds good

**Comment by rackgaming** [comment]
And for player owned vaults [bankname vault] namehere balance is good

**Comment by rackgaming** [comment]
So just make it when they place that sign on their chest its claimed to their name

**Comment by Rocologo** [comment]
I got another idea.

The admin/owner could place a NpC inside the bank, and if the player has no vault, the NPC could be used to claim a vault and then tell the player which vault number he got.

I could probably make the NPC to walk to the vault and show the player where it is. Maybe!

**Comment by rackgaming** [comment]
New issue: BagOfGold is not showing up on bedrock

**Comment by rackgaming** [comment]
like I can see they have it but on mobile side, they don't see it.

**Comment by Rocologo** [comment]
New issue - New ticket!  So we dont get confused.  If you are using Geyser,then open a ticket at their place. I think it is Geyser which does not support custom playerheads. I think I read that somewhere, and therefore it does not work :-(

Im still working on the Physical bank feature, but it takes time, because Xmas is very busy and more important :-)

**Comment by Rocologo** [comment]
Look here: https://github.com/GeyserMC/Geyser/issues/1454 

It seems to be a Bedrock limitation.
