### ISSUE TITLE
Bag disappear

### ISSUE THREAD

**Issue by wmelo92** [Rocologo/BagOfGold#82]
When I leave the bag in inventory and log out / soon, it disappears.

Using paperspigot, 1.14.4, via mysql

**Comment by wmelo92** [comment]
[16:21:18 ERROR]: Could not pass event PlayerQuitEvent to BagOfGold v2.8.6
java.lang.NullPointerException: null
at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:683) ~[patched_1.14.4.jar:git-Paper-214]
at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1043) ~[patched_1.14.4.jar:git-Paper-214]
at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5175) ~[patched_1.14.4.jar:git-Paper-214]
at one.lindegaard.BagOfGold.storage.DatabaseDataStore.loadPlayerSettings(DatabaseDataStore.java:234) ~[?:?]
at one.lindegaard.BagOfGold.PlayerSettingsManager.getPlayerSettings(PlayerSettingsManager.java:47) ~[?:?]
at one.lindegaard.BagOfGold.PlayerBalanceManager.onPlayerQuit(PlayerBalanceManager.java:162) ~[?:?]
at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_V(DirectHandle.java:177) ~[?:1.8.0_222]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-214]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-214]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:409) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.NetworkManager.handleDisconnection(NetworkManager.java:356) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:163) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-214]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-214]
at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]

**Comment by Rocologo** [comment]
1) make sure to use newest version.2) If you still have this bug, please provide me with the full error text. It looks like if something is missing?

**Comment by Rocologo** [comment]
no answer
