### ISSUE TITLE
[Issue/Feature Request] Balance going negative

### ISSUE THREAD

**Issue by PaisWillie** [Rocologo/BagOfGold#94]
Here is the [video](https://imgur.com/a/c7cUHgp) of what I did, and this is the debug output:

```
28.04 13:48:14 [Server] Server thread/INFO [BagOfGold] [Debug] Adjusting Player Balance to Amount of BagOfGold in Inventory: PlayerBalance: {player: Name:Sophias, WorldGrp:default, GameMode:SURVIVAL, Balance: 1.0(+0.0), BankBalance: 0.0(+0.0)}
28.04 13:48:14 [Server] Server thread/INFO [BagOfGold] [Debug] there was no difference
28.04 13:48:15 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=25)(2)
28.04 13:48:15 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
28.04 13:48:15 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance 1
28.04 13:48:18 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=26)(2)
28.04 13:48:18 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
28.04 13:48:18 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance 0
28.04 13:48:20 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=27)(2)
28.04 13:48:20 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
28.04 13:48:20 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance -1
28.04 13:48:24 [Server] Server thread/INFO Sophias issued server command: /bal
28.04 13:48:28 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias moved BagOfGold (1.0) out of Inventory
28.04 13:48:28 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance -2
28.04 13:48:31 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias moved BagOfGold (1.0) into Inventory
28.04 13:48:31 [Server] Server thread/INFO [BagOfGold] [Debug] Adding 1 to Sophias's balance -3
28.04 13:48:32 [Server] Server thread/INFO [BagOfGold] [Debug] Adjusting Player Balance to Amount of BagOfGold in Inventory: PlayerBalance: {player: Name:Sophias, WorldGrp:default, GameMode:SURVIVAL, Balance: -2.0(+0.0), BankBalance: 0.0(+0.0)}
28.04 13:48:32 [Server] Server thread/INFO [BagOfGold] [Debug] Adjusting Balance to amt: amt=1.0, inHand=0.0, bal=-2.0(+0.0)
28.04 13:48:32 [Server] Server thread/INFO [BagOfGold] [Debug] Adding 3 to Sophias's balance -2
28.04 13:48:34 [Server] Server thread/INFO Sophias issued server command: /bal
```

By the looks of it, the plugin does not correct your balance until you _close your inventory_. Just a suggestion, but maybe also make the plugin correct the player's balance every time they pick up the gold? (PlayerPickupItemEvent)

**Comment by Rocologo** [comment]
I'll have to look into this. :-) 

The idea about this plugin is that the bagofgold shouold work like physical money and you cant have a bag with a negative amount of coins in the bag :-)

**Comment by PaisWillie** [comment]
Yeah, I was hoping if you could prevent it from going negative when you drop the gold before your balance updates when you pick up the gold

**Comment by Rocologo** [comment]
I hope I can :-) and I will try to fix this.

**Comment by Rocologo** [comment]
Strange I still have another experience than you. When I do the exact same on your video, it works as it should. I end up with /bal = 1 

I dont understand why things works different on your server than on mine.

**Comment by Rocologo** [comment]
Ohhh I now see the debug information for the pickups is missing (PlayerPickupItemEvent) 

They are not missing on my server ???

**Comment by Rocologo** [comment]
I use the same server  Spigot 1.15.2 ..... hmmm

**Comment by Rocologo** [comment]
Do you get errors in the server log, when you start your server?

**Comment by PaisWillie** [comment]
My balance only updates when I **close my inventory**, if I just stand and wait, it doesn't update.

**Comment by PaisWillie** [comment]
Also, no errors, this is the only console output on startup:

```
[Server] Server thread/INFO [BagOfGold] Loading BagOfGold v2.9.7-SNAPSHOT-B394
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] Enabling BagOfGold v2.9.7-SNAPSHOT-B394
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] Config.yml was backed up to plugins/BagOfGold/backup/config.yml.bak26
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] Database version 3 detected.
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with ProtocolLib (4.5.0).
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] Compatibility with ActionAnnouncer is disabled in config.yml
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with PlaceholderAPI (2.10.5).
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] [BagOfGold][Economy] Vault found: Waiting
29.04 16:42:45 [Server] Server thread/INFO [BagOfGold] hooked into Vault
29.04 16:42:47 [Server] Server thread/INFO [Essentials] Payment method found (Vault - Economy: BagOfGold version: 1.7.2-b107)
29.04 16:42:48 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with Citizens2 (2.0.26-SNAPSHOT (build 1854))
```

**Comment by Rocologo** [comment]
We will need to find the difference between yours and mine server, before I can solve this. Im not able to guess why the pickup event is not caught.

**Comment by PaisWillie** [comment]
Message me on Discord (Wisdom#1500) and I can let you test it on my server some time, although it’s 3am for me right now

**Comment by Rocologo** [comment]
I dont need testing on your server. I trust you that it works like you said. (Or not work :-D) 

So we/I need to compare the two servers, to understand why the pickup event is not action the same way on the two servers.

**Comment by Rocologo** [comment]
I will probably have to make a snapshot with more debug information, to detect where it goes wrong.

**Comment by Rocologo** [comment]
And I am on work the next 7 hours, so you will have to be patient

**Comment by Rocologo** [comment]
Hi there. I have made a new build with a lot more debug information to tell me what happens. 

Please test this build and tell me if it says 
1) "EntityPickupItemEventListener registered"
or
2) "PlayerPickupItemEventListener registered" 
int he server log on server start 

and the pickup 1 BagOfGold and show me the debug information from the server log

https://fractal.lindegaard.one:8181/job/BagOfGold/395/

**Comment by PaisWillie** [comment]
I got **EntityPickupItemEventListener registered**.
```
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] Enabling BagOfGold v2.9.7-SNAPSHOT-B395
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] Config.yml was backed up to plugins/BagOfGold/backup/config.yml.bak30
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] bStat is enabled
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] Initialize database
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] Database version 3 detected.
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] MoneyMergeEvent: Registered
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] EntityPickupItemEventListener registered
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with ProtocolLib (4.5.0).
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] Compatibility with ActionAnnouncer is disabled in config.yml
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with PlaceholderAPI (2.10.5).
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] PlaceHolderManager started
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [BagOfGold][Economy] Vault found: Waiting
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] Number of Vault Economy Providers = 2
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] Vault Economy provider name=BagOfGold
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] [Debug] Vault Economy provider name=Essentials Economy
30.04 12:44:12 [Server] Server thread/INFO [BagOfGold] hooked into Vault
30.04 12:44:14 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with Essentials (2.17.2.0)
30.04 12:44:14 [Server] Server thread/INFO [Essentials] Payment method found (Vault - Economy: BagOfGold version: 1.7.2-b107)
30.04 12:44:15 [Server] Server thread/INFO [BagOfGold] Enabling compatibility with Citizens2 (2.0.26-SNAPSHOT (build 1854))
30.04 12:44:52 [Server] Craft Scheduler Thread - 3/INFO [BagOfGold] [Debug] PlayerBalanceManager: loading Sophias balance (default,SURVIVAL) from DB
30.04 12:44:52 [Server] Craft Scheduler Thread - 3/INFO [BagOfGold] [Debug] PlayerBalanceManager: loading WisdomGamer balance (default,SURVIVAL) from DB
30.04 12:44:52 [Server] Craft Scheduler Thread - 3/INFO [BagOfGold] [Debug] PlayerBalanceManager: loading Wealthier balance (default,SURVIVAL) from DB
30.04 12:44:52 [Server] Craft Scheduler Thread - 1/INFO [BagOfGold] [Debug] PlayerBalanceManager: loading Wealthier balance (default,SURVIVAL) from DB
30.04 12:44:52 [Server] Craft Scheduler Thread - 3/INFO [BagOfGold] [Debug] PlayerBalanceManager: loading sprucemoose03 balance (default,SURVIVAL) from DB
30.04 12:44:56 [Server] Server thread/INFO [BagOfGold] [Debug] Citizens2 was enabled
```

I dropped and picked up the BagOfGold twice, intially having only $1, and now i have $-1. It wasn't until I opened and closed my inventory until my balance corrected itself. 


```
30.04 12:47:35 [Server] Server thread/INFO [BagOfGold] [Debug] Adjusting Player Balance to Amount of BagOfGold in Inventory: PlayerBalance: {player: Name:Sophias, WorldGrp:default, GameMode:SURVIVAL, Balance: 1.0(+0.0), BankBalance: 0.0(+0.0)}
30.04 12:47:35 [Server] Server thread/INFO [BagOfGold] [Debug] there was no difference
30.04 12:47:36 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=1)(2)
30.04 12:47:36 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
30.04 12:47:36 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance 1
30.04 12:47:38 [Server] Server thread/INFO [BagOfGold] [Debug] EntityPickupItemEvent called
30.04 12:47:38 [Server] Server thread/INFO [BagOfGold] [Debug] Player didn't pickup a reward.
30.04 12:47:39 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=2)(2)
30.04 12:47:39 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
30.04 12:47:39 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance 0
30.04 12:47:41 [Server] Server thread/INFO [BagOfGold] [Debug] EntityPickupItemEvent called
30.04 12:47:41 [Server] Server thread/INFO [BagOfGold] [Debug] Player didn't pickup a reward.
30.04 12:47:52 [Server] Server thread/INFO [BagOfGold] [Debug] Adjusting Player Balance to Amount of BagOfGold in Inventory: PlayerBalance: {player: Name:Sophias, WorldGrp:default, GameMode:SURVIVAL, Balance: -1.0(+0.0), BankBalance: 0.0(+0.0)}
30.04 12:47:52 [Server] Server thread/INFO [BagOfGold] [Debug] Adjusting Balance to amt: amt=1.0, inHand=0.0, bal=-1.0(+0.0)
30.04 12:47:52 [Server] Server thread/INFO [BagOfGold] [Debug] Adding 2 to Sophias's balance -1
```

It seems like the event is running, but it is not detecting the player skull as BagOfGold. Could it be because I renamed the BagOfGold to Bells in the config.yml file?

```
drop-money-on-ground-skull-reward-name: Bells
drop-money-on-ground-skull-reward-name-plural: Bells
```

**Comment by Rocologo** [comment]
This is the problem

Player didn't pickup a reward.

Now I need to dig into the code to see why it says its not a BagOgGold you pickup but stiil you can drop it emidiately after were it says it is... I will check the code again...

I dont think it is the name, because I have renamed it to Coins :-)

**Comment by Rocologo** [comment]
So I removed some debug information and added some and if I am lucky I might have found the problem. 

Please redo the test and show me the output when you pick up 1 bag/bells

https://fractal.lindegaard.one:8181/job/BagOfGold/396/

**Comment by PaisWillie** [comment]
I dropped it twice:
```
30.04 14:22:12 [Server] Server thread/INFO [BagOfGold] [Debug] Lore(2)=Hidden(2):b3f74fad-429f-4801-9e31-b8879cbae96f
30.04 14:22:12 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=true
30.04 14:22:12 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=3)(2)
30.04 14:22:12 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
30.04 14:22:12 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance 1
30.04 14:22:15 [Server] Server thread/INFO [BagOfGold] [Debug] Pickup item=ItemStack{AIR x 0}
30.04 14:22:15 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=false
30.04 14:22:15 [Server] Server thread/INFO [BagOfGold] [Debug] Player didn't pickup a reward.
30.04 14:22:16 [Server] Server thread/INFO [BagOfGold] [Debug] Lore(2)=Hidden(2):b3f74fad-429f-4801-9e31-b8879cbae96f
30.04 14:22:16 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=true
30.04 14:22:16 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1 Bells. (# of rewards left=4)(2)
30.04 14:22:16 [Server] Server thread/INFO [BagOfGold] [Debug] Sophias dropped 1.0 Bells using Q key
30.04 14:22:16 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from Sophias's balance 0
30.04 14:22:18 [Server] Server thread/INFO [BagOfGold] [Debug] Pickup item=ItemStack{AIR x 0}
30.04 14:22:18 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=false
30.04 14:22:18 [Server] Server thread/INFO [BagOfGold] [Debug] Player didn't pickup a reward.
```

**Comment by Rocologo** [comment]
I have an idea about what wrong, so I have changed the MetaData (so T1=true in the debuging)

Could you please test this build?

https://fractal.lindegaard.one:8181/job/BagOfGold/399/

And show me the debug information?

(Its very annoying that this bug does not happen on my own test-servers)

**Comment by Rocologo** [comment]
Or this one: https://fractal.lindegaard.one:8181/job/BagOfGold/400/

**Comment by PaisWillie** [comment]
```
30.04 18:54:12 [Server] Server thread/INFO [BagOfGold] [Debug] Lore(2)=Hidden(2):b3f74fad-429f-4801-9e31-b8879cbae96f
30.04 18:54:12 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=true
30.04 18:54:12 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer dropped 1 Bells. (# of rewards left=1)(2)
30.04 18:54:12 [Server] Server thread/ERROR Could not pass event PlayerDropItemEvent to BagOfGold v2.9.8-SNAPSHOT-B400
30.04 18:54:12 [Server] INFO org.bukkit.event.EventException: null
30.04 18:54:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.a(EntityHuman.java:597) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:1647) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.n(EntityHuman.java:552) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1181) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
30.04 18:54:12 [Server] INFO Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.ChatColor.GOLDBells
30.04 18:54:12 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
30.04 18:54:12 [Server] INFO at org.bukkit.ChatColor.valueOf(ChatColor.java:1) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.onPlayerDropReward(BagOfGoldItems.java:568) ~[?:?]
30.04 18:54:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
30.04 18:54:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
30.04 18:54:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
30.04 18:54:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
30.04 18:54:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
30.04 18:54:12 [Server] INFO ... 20 more
30.04 18:54:14 [Server] Server thread/INFO [BagOfGold] [Debug] Pickup item=ItemStack{AIR x 0}
30.04 18:54:14 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=false
30.04 18:54:14 [Server] Server thread/INFO [BagOfGold] [Debug] Player didn't pickup a reward.
```

**Comment by Rocologo** [comment]
Oh no. I made a TYPO :-(

I will make a new build immidiately

**Comment by Rocologo** [comment]
I have fixed the TYPO in this build: 

https://fractal.lindegaard.one:8181/job/BagOfGold/401/

But I am pretty sure that it will not solve the problem. After sleeping on this I realize that, we will find the problem when looking into this debug information:

30.04 18:54:14 [Server] Server thread/INFO [BagOfGold] [Debug] Pickup item=ItemStack{AIR x 0}

My event says you pickup AIR and we both know that you pickup a PLAYER_HEAD, so It could be another plugin making interference.... Maybe another plugin removed the item before BagOfGold plugin get the item.

**Comment by Rocologo** [comment]
Do you have any plugins which manipulate Heads or Inventories ? I think you posted a list of your plugins somewhere, but I cant find it?

**Comment by PaisWillie** [comment]
```
AcceptTheRules v2.3
ActionAnnouncer v1.15.0
AdvancedFood v3.6.4
AdvancedRegionMarket v3.0.2
AnimatedFrames v4.11.5-SNAPSHOT
AntiXrayHeuristics v1.2.0
ArmorStandTools v3.5.1
AsyncWorldEdit v3.6.19
BagOfGold v2.9.6
BannerBoard v1.10.3
BuycraftX v12.0.6
Citizens v2.0.26-SNAPSHOT (build 1854)
CitizensCMD v2.4
ClearLag v3.1.6
CommandButtons v4.2.1
CommandSpy v2.0
CoreProtect v2.18.2
DeathMessagesPrime v1.15.3
DeluxeChat v1.15.0
DeluxeCommands v1.10.0
DeluxeJoin v2.8.0
DeluxeMentions v3.0.6
DeluxeTags v1.8.1
DiscordSRV v1.18.4
EpicRename v3.7.1
Essentials v2.17.2.0
EssentialsAntiBuild v2.17.2.0
EssentialsProtect v2.17.2.0
EssentialsSpawn v2.17.2.0
FabledSkyBlock v2.2.8
FeatherBoard v4.25.0
FogusCore v1.9.9
GrantX v1.4.0
GSit v[2.12.0.0]
HeadDatabase v4.12.1
HeapDump v1.4.0
HolographicChat v0.1
HolographicDisplays v2.4.1
HolographicPlaceholders v2.0.1 Beta
InsaneShops v1.1.9
InteractionVisualizer v1.10.7
InteractiveChat v2.0.5
LeaderHeadsRevamped v4.0.5
LightAPI v3.4.2
LimitPillagers v2.12.0
LiteBans v2.4.7
LuckPerms v5.0.94
LuckPermsGUI v3.5
MapManager v1.7.8-SNAPSHOT
Matrix v4.7.8
mcMMO v2.1.124
MessageAnnouncer v1.11.0
MobFarmManager v1.5.5.1
MovingDevApi v1.1.3
Multiverse-Core v4.1.0-b775
Multiverse-Inventories v3.0.0-b459
Multiverse-NetherPortals v4.1.0-b763
Multiverse-Portals v4.1.0-b805
MVdWPlaceholderAPI v3.0.1
OnTime v4.1.4
OreoCore v14.7
PacketListenerApi v3.7.5-SNAPSHOT
PlaceholderAPI v2.10.5
PlayerReport v3.2.12
PlugMan v2.1.7
PremiumVanish v2.5.11
ProtocolLib v4.5.0
RewardPRO v4.2.3
SelectionVisualizer v3.0.0.7
ServerTutorialPlus v1.21.3
SilkSpawners v6.0.0-SNAPSHOT-b${BUILD_NUMBER}
Skript v2.4.1
TAB v2.7.4
TaskScheduler v1.0
TokenManager v3.2.5
TradeSystem v1.1.8
TrMenu v1.21
UltimateStacker v1.11.7
Vault v1.7.2-b107
ViaBackwards v3.0.0-SNAPSHOT
ViaVersion v3.0.0-SNAPSHOT
VillagerOptimiser v1.1.2
Votifier v2.6.0-SNAPSHOT
Voting v2.5.0
VotingPlugin v5.21.1
WorldBorder v1.9.10 (beta)
WorldEdit v7.1.0;8e55131
WorldGuard v7.0.2-SNAPSHOT;bf2593e
WorldGuardExtraFlags v4.1.4
XProtect v2.5.1
```

**Comment by Rocologo** [comment]
Have you had time to test newest build? Im leaving work now, so I will have some time to look at this.

https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by PaisWillie** [comment]
You fixed it!

Dropping & picking it up twice:
```
01.05 12:23:23 [Server] Server thread/INFO [BagOfGold] [Debug] Lore(2)=Hidden(2):b3f74fad-429f-4801-9e31-b8879cbae96f
01.05 12:23:23 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=true
01.05 12:23:23 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer dropped 1 Bells. (# of rewards left=1)(2)
01.05 12:23:23 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer dropped 1.0 Bells using Q key
01.05 12:23:23 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from WisdomGamer's balance 1
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] Pickup item=ItemStack{AIR x 0}
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=true, Lores T2=false
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] A player picked up the reward.
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=true, Lores T2=false
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] PickupRewards: This is a reward.
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer has room for 3199968.0 BagOfGold in the inventory
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] Deposit 1 to WisdomGamer's account, new balance is 1
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] PickupRewards succes=true
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] Remove item from ground
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer picked up a Bells with a value:1 (# of rewards left=0)(PickupRewards)
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] Call rewardPlayer
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] Lore(2)=Hidden(2):b3f74fad-429f-4801-9e31-b8879cbae96f
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=false, Lores T2=true
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer dropped 1 Bells. (# of rewards left=1)(2)
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer dropped 1.0 Bells using Q key
01.05 12:23:25 [Server] Server thread/INFO [BagOfGold] [Debug] Removing 1 from WisdomGamer's balance 1
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] Pickup item=ItemStack{AIR x 0}
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=true, Lores T2=false
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] A player picked up the reward.
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] MetaData T1=true, Lores T2=false
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] PickupRewards: This is a reward.
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer has room for 3199968.0 BagOfGold in the inventory
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] Deposit 1 to WisdomGamer's account, new balance is 1
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] PickupRewards succes=true
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] Remove item from ground
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] WisdomGamer picked up a Bells with a value:1 (# of rewards left=0)(PickupRewards)
01.05 12:23:27 [Server] Server thread/INFO [BagOfGold] [Debug] Call rewardPlayer
```

**Comment by Rocologo** [comment]
Okay. I'm not completly satisfied because og the AIR thing but it is better. I will remove the extra debug info an make a real release. There might be others who have this problem. 

Thank you for your patience
